### PR TITLE
Provenance without external dependencies

### PR DESCRIPTION
**Pull request by shark8me**
I've created a utility class to generate provenance for publishing, which doesn't need external dependencies.

Excuse my rather basic Java :).

### CODE REVIEW

**Comment by mikera** [comment]
Looks reasonably sensible at first glance but why are we using JSONObject instead of Map<String,Object> as we do elsewhere in the starfish API? Any strong reasons?

**Comment by shark8me** [comment]
I used JSONObject/JSONValue because that's what https://github.com/DEX-Company/starfish-java/blob/develop/src/main/java/sg/dex/starfish/util/JSON.java seems to use. 
Did you mean that the interface should not expose JSONObject, and instead use standard Java (Map<String,Object>) ?

**Comment by mikera** [comment]
I think it's only being used for the Parser. In general, the API uses plain java maps.

**Comment by shark8me** [comment]
I've changed the API to use Map<String,Object> instead of JSONObject.

**Pull request merged**
